import type { Agent } from "./slices/agentsSlice"
import type { MarketplaceAgent } from "./slices/marketplaceSlice"

export const dummyAgents: Agent[] = [
  {
    id: "1",
    name: "SalesGPT",
    role: "Sales Representative",
    description: "AI-powered sales agent that handles client interactions and closes deals",
    personality: "Persuasive, professional, results-oriented",
    status: "active",
    lastActive: "2 minutes ago",
    conversationCount: 342,
    tasksCompleted: 1203,
    avatar: "🤖",
  },
  {
    id: "2",
    name: "SupportGPT",
    role: "Customer Support Specialist",
    description: "Handles customer inquiries, issues, and provides technical support",
    personality: "Empathetic, patient, solution-focused",
    status: "active",
    lastActive: "1 minute ago",
    conversationCount: 521,
    tasksCompleted: 1859,
    avatar: "💬",
  },
  {
    id: "3",
    name: "MarketingGPT",
    role: "Marketing Manager",
    description: "Creates campaigns, analyzes metrics, and drives growth",
    personality: "Creative, data-driven, strategic",
    status: "inactive",
    lastActive: "1 hour ago",
    conversationCount: 156,
    tasksCompleted: 432,
    avatar: "📊",
  },
  {
    id: "4",
    name: "HR-Assistant",
    role: "HR Specialist",
    description: "Manages recruitment, onboarding, and employee inquiries",
    personality: "Organized, supportive, process-oriented",
    status: "active",
    lastActive: "5 minutes ago",
    conversationCount: 89,
    tasksCompleted: 234,
    avatar: "👥",
  },
]

export const dummyMarketplaceAgents: MarketplaceAgent[] = [
  {
    id: "m1",
    name: "ContentGPT Pro",
    description: "Professional content creation and copywriting agent",
    category: "Content",
    rating: 4.8,
    downloads: 3421,
    price: 99,
    isPaid: true,
    avatar: "✍️",
    createdBy: "ContentTeam",
  },
  {
    id: "m2",
    name: "DataAnalyzer",
    description: "Advanced data analysis and reporting automation",
    category: "Analytics",
    rating: 4.9,
    downloads: 2156,
    price: 0,
    isPaid: false,
    avatar: "📈",
    createdBy: "DataLabs",
  },
  {
    id: "m3",
    name: "EmailCampaigner",
    description: "Automated email marketing and campaign management",
    category: "Marketing",
    rating: 4.7,
    downloads: 1834,
    price: 49,
    isPaid: true,
    avatar: "📧",
    createdBy: "MarketingPro",
  },
  {
    id: "m4",
    name: "CodeAssistant",
    description: "AI coding assistant for development teams",
    category: "Development",
    rating: 4.9,
    downloads: 5234,
    price: 0,
    isPaid: false,
    avatar: "💻",
    createdBy: "DevTools",
  },
  {
    id: "m5",
    name: "LeadQualifier",
    description: "Intelligent lead scoring and qualification system",
    category: "Sales",
    rating: 4.6,
    downloads: 892,
    price: 149,
    isPaid: true,
    avatar: "🎯",
    createdBy: "SalesFlow",
  },
  {
    id: "m6",
    name: "ChatBot Express",
    description: "Fast and easy chatbot creation for websites",
    category: "Customer Service",
    rating: 4.5,
    downloads: 2341,
    price: 0,
    isPaid: false,
    avatar: "🤖",
    createdBy: "ChatTech",
  },
]
